name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "We do not accept PRs. Please check out the [README](https://github.com/modularml/devrel-extras?tab=readme-ov-file#developer-releations-extras)"
